version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: tmap_postgres
    environment:
      POSTGRES_DB: codingTest
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build: .
    container_name: tmap_app
    ports:
      - "3535:3535"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  postgres_data:
